package elevio

var MY_ID int
var LocalElevator Elevator

const (
	NUM_ELEVATORS = 3
	NUM_FLOORS    = 4

	BCAST_PORT = 16569

	// all ms
	ELEVATOR_TIMEOUT  = 7000
	TRAVEL_TIME       = 2500
	DOOR_OPEN_TIME    = 3000
	BIDDING_TIME      = 500
	BIDDING_MIN_RAISE = 100
	IS_ALONE_TIMEOUT  = 500
	BROADCAST_PERIOD  = 50
)
